export const WEB_CHECK_SCAN_PRESETS = [
  {
    id: 'web',
    label: 'Web Preset',
    description: 'Lean website triage: trust, exposure, headers, TLS, DNS, and visual context.',
    cyberbroPreset: 'web',
    jobIds: [
      'get-ip',
      'location',
      'ssl',
      'whois',
      'quality',
      'tech-stack',
      'headers',
      'dns',
      'http-security',
      'tls-connection',
      'security-txt',
      'dnssec',
      'hsts',
      'threats',
      'cyberbro',
      'redirects',
      'robots-txt',
      'status',
      'block-lists',
      'sitemap',
      'screenshot',
      'social-tags',
    ],
  },
  {
    id: 'cyber_intel',
    label: 'Cyber Intel Preset',
    description: 'Security-heavy enrichment for suspicious domains, URLs, IPv4, and IPv6.',
    cyberbroPreset: 'cyber_intel',
    jobIds: [
      'get-ip',
      'location',
      'ssl',
      'whois',
      'tech-stack',
      'headers',
      'dns',
      'http-security',
      'tls-connection',
      'tls-labs',
      'subdomains',
      'trace-route',
      'security-txt',
      'dns-server',
      'firewall',
      'dnssec',
      'hsts',
      'threats',
      'cyberbro',
      'mail-config',
      'archives',
      'redirects',
      'status',
      'ports',
      'txt-records',
      'block-lists',
    ],
  },
  {
    id: 'full_surface',
    label: 'Full Surface',
    description: 'Run the broadest Web Check sweep plus Cyberbro for deep investigations.',
    cyberbroPreset: 'cyber_intel',
    jobIds: [
      'get-ip',
      'location',
      'ssl',
      'whois',
      'quality',
      'tech-stack',
      'shodan',
      'cookies',
      'headers',
      'dns',
      'http-security',
      'tls-connection',
      'tls-labs',
      'subdomains',
      'trace-route',
      'security-txt',
      'dns-server',
      'firewall',
      'dnssec',
      'hsts',
      'threats',
      'cyberbro',
      'mail-config',
      'archives',
      'rank',
      'redirects',
      'linked-pages',
      'robots-txt',
      'status',
      'ports',
      'txt-records',
      'block-lists',
      'sitemap',
      'screenshot',
      'social-tags',
      'carbon',
    ],
  },
  {
    id: 'custom',
    label: 'Custom',
    description: 'Choose exactly which Web Check jobs and Cyberbro profile should run.',
    cyberbroPreset: 'web',
    jobIds: [],
  },
];

export const webCheckScanPresetMap = Object.fromEntries(
  WEB_CHECK_SCAN_PRESETS.map((preset) => [preset.id, preset]),
);

export const getScanPreset = (presetId: string | undefined | null) =>
  webCheckScanPresetMap[String(presetId || '').toLowerCase()] || WEB_CHECK_SCAN_PRESETS[0];
